// Made by scripts/build-manifest.js (npm run build:manifest), don't edit: every file the game
// downloads before it starts, in groups, with each file's size in bytes (paths from the page), so
// the loading screen can show exactly how far it has got. test/manifest.test.js checks it's up to
// date.

export const MANIFEST = Object.freeze([
    {
        id: "engine",
        label: "3D engine",
        detail: "Three.js r186",
        files: [
            ["vendor/meshoptimizer-1.3.0/meshopt_simplifier.min.js", 53692],
            ["vendor/three-r186/addons/environments/RoomEnvironment.js", 2145],
            ["vendor/three-r186/addons/loaders/GLTFLoader.js", 45403],
            ["vendor/three-r186/addons/utils/BufferGeometryUtils.js", 13537],
            ["vendor/three-r186/addons/utils/SkeletonUtils.js", 4123],
            ["vendor/three-r186/three.core.min.js", 389591],
            ["vendor/three-r186/three.module.min.js", 376189],
        ],
    },
    {
        id: "navigation",
        label: "Ways over the world",
        detail: "Recast and Detour (recast-navigation-js 0.43.1)",
        files: [
            ["vendor/recast-navigation-0.43.1/core.min.mjs", 49173],
            ["vendor/recast-navigation-0.43.1/recast-navigation.wasm.js", 559543],
            ["vendor/recast-navigation-0.43.1/recast-navigation.wasm.wasm", 338824],
        ],
    },
    {
        id: "code",
        label: "Game code",
        detail: "Pellagos",
        files: [
            ["js/app/camera.js", 5451],
            ["js/app/creator.js", 27453],
            ["js/app/doors.js", 9133],
            ["js/app/fate.js", 4610],
            ["js/app/game.js", 229198],
            ["js/app/gearinfo.js", 8053],
            ["js/app/governor.js", 6328],
            ["js/app/heroes.js", 7619],
            ["js/app/hud.js", 11533],
            ["js/app/icons.js", 56225],
            ["js/app/journal.js", 9359],
            ["js/app/mapicons.js", 5524],
            ["js/app/minimap.js", 33690],
            ["js/app/pacing.js", 1893],
            ["js/app/pack.js", 42492],
            ["js/app/predict.js", 6326],
            ["js/app/session.js", 3586],
            ["js/app/spellbook.js", 7354],
            ["js/app/spellicons.js", 52938],
            ["js/app/talk.js", 3448],
            ["js/app/together.js", 14673],
            ["js/app/wheel.js", 15271],
            ["js/app/wheelsetup.js", 6795],
            ["js/app/worldmap.js", 24805],
            ["js/audio/dsp.js", 7151],
            ["js/audio/instruments.js", 2904],
            ["js/audio/samples.js", 3847],
            ["js/audio/score.js", 12468],
            ["js/audio/sound.js", 34497],
            ["js/audio/synth.js", 22503],
            ["js/audio/tavern.js", 11520],
            ["js/audio/worker.js", 958],
            ["js/beasts/arachnid.js", 16991],
            ["js/beasts/beast.js", 22658],
            ["js/beasts/biped.js", 27624],
            ["js/beasts/blob.js", 14220],
            ["js/beasts/bones.js", 17980],
            ["js/beasts/cloth.js", 7977],
            ["js/beasts/flyers.js", 15725],
            ["js/beasts/looks.js", 21066],
            ["js/beasts/quadruped.js", 57885],
            ["js/beasts/sculpt.js", 32939],
            ["js/beasts/serpent.js", 9125],
            ["js/beasts/shapes.js", 7215],
            ["js/characters/actions.js", 197317],
            ["js/characters/body.js", 8434],
            ["js/characters/character.js", 49615],
            ["js/characters/details.js", 7649],
            ["js/characters/drapes.js", 19254],
            ["js/characters/equipment.js", 25417],
            ["js/characters/face.js", 3403],
            ["js/characters/folk.js", 20138],
            ["js/characters/gait.js", 8036],
            ["js/characters/garments.js", 88492],
            ["js/characters/hair.js", 47550],
            ["js/characters/items.js", 56000],
            ["js/characters/kit.js", 1637],
            ["js/characters/liveries.js", 7158],
            ["js/characters/locomotion.js", 27427],
            ["js/characters/lod-worker.js", 416],
            ["js/characters/lod.js", 4583],
            ["js/characters/macro.js", 6921],
            ["js/characters/noise.js", 3762],
            ["js/characters/pack.js", 3799],
            ["js/characters/peoples.js", 10210],
            ["js/characters/presets.js", 9955],
            ["js/characters/rig.js", 37119],
            ["js/characters/skin-worker.js", 1731],
            ["js/characters/skin.js", 33356],
            ["js/characters/skins.js", 5617],
            ["js/characters/soldiers.js", 2347],
            ["js/characters/surfaces.js", 7002],
            ["js/core/afflictions.js", 3195],
            ["js/core/battle.js", 121953],
            ["js/core/creatures.js", 15048],
            ["js/core/dialogue.js", 73150],
            ["js/core/exact.js", 5437],
            ["js/core/explored.js", 2779],
            ["js/core/fields.js", 5397],
            ["js/core/gear.js", 17322],
            ["js/core/grid.js", 2643],
            ["js/core/host.js", 161947],
            ["js/core/insides.js", 38745],
            ["js/core/interiors.js", 16423],
            ["js/core/lore/gods.js", 4981],
            ["js/core/lore/taverns.js", 6121],
            ["js/core/motion.js", 5466],
            ["js/core/names.js", 3885],
            ["js/core/navigation.js", 17492],
            ["js/core/navigation/bake.js", 6730],
            ["js/core/navigation/recast.js", 1261],
            ["js/core/navigation/settings.js", 2509],
            ["js/core/navigation/squares.js", 2271],
            ["js/core/navigation/tiles.js", 11140],
            ["js/core/netplay.js", 25530],
            ["js/core/noise.js", 2506],
            ["js/core/overworld.js", 56295],
            ["js/core/progress.js", 37652],
            ["js/core/random.js", 4020],
            ["js/core/roles.js", 11023],
            ["js/core/setpieces/castle.js", 15029],
            ["js/core/setpieces/neutral.js", 16849],
            ["js/core/setpieces/pieces.js", 8596],
            ["js/core/setpieces/plan.js", 4271],
            ["js/core/setpieces/town.js", 50725],
            ["js/core/settlements.js", 8967],
            ["js/core/sites.js", 28000],
            ["js/core/spells.js", 22498],
            ["js/core/spoils.js", 11216],
            ["js/core/standing.js", 27913],
            ["js/core/steps.js", 2973],
            ["js/core/terrain/curve.js", 2252],
            ["js/core/terrain/flats.js", 3355],
            ["js/core/terrain/ground.js", 20902],
            ["js/core/terrain/height.js", 19680],
            ["js/core/terrain/simplex.js", 4122],
            ["js/core/terrain/waters.js", 32775],
            ["js/core/terrain/ways.js", 6635],
            ["js/core/trails.js", 11151],
            ["js/core/variety.js", 1431],
            ["js/core/war/muster.js", 6955],
            ["js/core/war/news.js", 8016],
            ["js/core/war/peoples.js", 5272],
            ["js/core/war/roads.js", 4989],
            ["js/core/war/war.js", 59469],
            ["js/core/wilds.js", 17115],
            ["js/core/world.js", 9994],
            ["js/core/worldplan/plan.js", 7443],
            ["js/core/worldplan/queue.js", 2536],
            ["js/core/worldplan/races.js", 7862],
            ["js/core/worldplan/settle.js", 25034],
            ["js/core/worldplan/terrain.js", 19322],
            ["js/world/ailments3d.js", 12074],
            ["js/world/art/engine/atlas.js", 24650],
            ["js/world/art/engine/materials.js", 4856],
            ["js/world/art/engine/models.js", 2772],
            ["js/world/art/engine/paint-worker.js", 416],
            ["js/world/art/engine/painters.js", 53061],
            ["js/world/art/engine/solid.js", 53194],
            ["js/world/art/kits/castle.js", 23981],
            ["js/world/art/kits/decay.js", 20403],
            ["js/world/art/kits/emblems.js", 22704],
            ["js/world/art/kits/framing.js", 9824],
            ["js/world/art/kits/hedges.js", 24638],
            ["js/world/art/kits/house.js", 38272],
            ["js/world/art/kits/landmarks.js", 33842],
            ["js/world/art/kits/leftovers.js", 9284],
            ["js/world/art/kits/neutral.js", 30773],
            ["js/world/art/kits/props.js", 12550],
            ["js/world/art/kits/roofs.js", 11099],
            ["js/world/art/kits/signs.js", 17966],
            ["js/world/art/kits/town.js", 702],
            ["js/world/art/kits/trees.js", 76129],
            ["js/world/art/kits/wilds.js", 120893],
            ["js/world/art/peoples/camp.js", 7887],
            ["js/world/art/peoples/cat-landmarks.js", 36071],
            ["js/world/art/peoples/cat-places.js", 28537],
            ["js/world/art/peoples/cat.js", 38554],
            ["js/world/art/peoples/darkelf.js", 41604],
            ["js/world/art/peoples/elf.js", 44495],
            ["js/world/art/peoples/index.js", 2572],
            ["js/world/art/peoples/kit.js", 25332],
            ["js/world/art/peoples/lizard-places.js", 38367],
            ["js/world/art/peoples/lizard.js", 19771],
            ["js/world/art/peoples/orc-places.js", 37486],
            ["js/world/art/peoples/orc.js", 22680],
            ["js/world/art/peoples/props.js", 20408],
            ["js/world/art/peoples/sylvan.js", 14693],
            ["js/world/avatar.js", 7991],
            ["js/world/banners3d.js", 10055],
            ["js/world/camps3d.js", 8740],
            ["js/world/chunks3d.js", 40855],
            ["js/world/contacts.js", 5328],
            ["js/world/drops3d.js", 6240],
            ["js/world/effects.js", 60966],
            ["js/world/environment.js", 4345],
            ["js/world/falls.js", 12088],
            ["js/world/far/far-worker.js", 1096],
            ["js/world/far/far.js", 6346],
            ["js/world/far/gather.js", 3284],
            ["js/world/far/levels.js", 3747],
            ["js/world/far/rivers.js", 2688],
            ["js/world/far/shapes.js", 23013],
            ["js/world/far/silhouette-worker.js", 2323],
            ["js/world/far/silhouettes.js", 11760],
            ["js/world/far/trees.js", 7972],
            ["js/world/far/volcano.js", 15432],
            ["js/world/fields.js", 2813],
            ["js/world/flyers3d.js", 24738],
            ["js/world/fog.js", 7842],
            ["js/world/gputimer.js", 2649],
            ["js/world/grass.js", 17234],
            ["js/world/grassmap.js", 15921],
            ["js/world/ground.js", 61304],
            ["js/world/interiors3d.js", 100435],
            ["js/world/layout-worker.js", 357],
            ["js/world/layouts.js", 2729],
            ["js/world/look.js", 8102],
            ["js/world/motes.js", 8863],
            ["js/world/navbaker.js", 4364],
            ["js/world/navview.js", 5258],
            ["js/world/navworker.js", 549],
            ["js/world/shadows.js", 2448],
            ["js/world/sky.js", 6856],
            ["js/world/spellfx.js", 85142],
            ["js/world/squares.js", 6596],
            ["js/world/sun.js", 1253],
            ["js/world/terrain-worker.js", 1089],
            ["js/world/terrains.js", 3972],
            ["js/world/town3d.js", 21748],
            ["js/world/view.js", 41891],
            ["js/world/water.js", 20155],
            ["js/world/wounds.js", 32881],
        ],
    },
    {
        id: "body",
        label: "Body and shapes",
        detail: "MakeHuman base mesh, skeleton and sliders",
        files: [
            ["characters/human.bin", 1516649],
            ["characters/human.json", 137383],
        ],
    },
    {
        id: "skin",
        label: "Skin details",
        detail: "MakeHuman masks",
        files: [
            ["characters/masks/aureolae.jpg", 17232],
            ["characters/masks/crotch.jpg", 24810],
            ["characters/masks/ears.jpg", 18900],
            ["characters/masks/eyelids.jpg", 22684],
            ["characters/masks/fingernails.jpg", 18321],
            ["characters/masks/lips.jpg", 20552],
            ["characters/masks/toenails.jpg", 17589],
        ],
    },
    {
        id: "fonts",
        label: "Lettering",
        detail: "UnifrakturMaguntia, for the tavern's signs",
        files: [
            ["fonts/UnifrakturMaguntia.woff2", 26512],
        ],
    },
]);
