// Made by scripts/build-manifest.js (npm run build:manifest), don't edit: every file the game
// downloads before it starts, in groups, with each file's size in bytes (paths from the page), so
// the loading screen can show exactly how far it has got. test/manifest.test.js checks it's up to
// date.

export const MANIFEST = Object.freeze([
    {
        id: "engine",
        label: "3D engine",
        detail: "Three.js r186",
        files: [
            ["vendor/three-r186/addons/environments/RoomEnvironment.js", 2145],
            ["vendor/three-r186/addons/loaders/GLTFLoader.js", 45403],
            ["vendor/three-r186/addons/utils/BufferGeometryUtils.js", 13537],
            ["vendor/three-r186/addons/utils/SkeletonUtils.js", 4123],
            ["vendor/three-r186/three.core.min.js", 389591],
            ["vendor/three-r186/three.module.min.js", 376189],
        ],
    },
    {
        id: "code",
        label: "Game code",
        detail: "Pellagos",
        files: [
            ["js/app/creator.js", 23947],
            ["js/app/game.js", 25837],
            ["js/app/heroes.js", 5479],
            ["js/app/hud.js", 5297],
            ["js/app/session.js", 1317],
            ["js/characters/actions.js", 35290],
            ["js/characters/body.js", 8056],
            ["js/characters/character.js", 17953],
            ["js/characters/details.js", 5742],
            ["js/characters/equipment.js", 10113],
            ["js/characters/face.js", 3403],
            ["js/characters/gait.js", 7667],
            ["js/characters/garments.js", 49067],
            ["js/characters/hair.js", 25618],
            ["js/characters/items.js", 18366],
            ["js/characters/kit.js", 829],
            ["js/characters/locomotion.js", 23941],
            ["js/characters/macro.js", 6921],
            ["js/characters/noise.js", 2651],
            ["js/characters/pack.js", 3799],
            ["js/characters/presets.js", 3250],
            ["js/characters/rig.js", 18534],
            ["js/characters/skin.js", 23724],
            ["js/core/battle.js", 25368],
            ["js/core/pathfinding.js", 6003],
            ["js/core/random.js", 3611],
            ["js/core/setpieces/pieces.js", 5061],
            ["js/core/setpieces/plan.js", 4271],
            ["js/core/setpieces/town.js", 13418],
            ["js/core/world.js", 8093],
            ["js/world/art/engine/materials.js", 16244],
            ["js/world/art/engine/models.js", 2772],
            ["js/world/art/engine/solid.js", 9484],
            ["js/world/art/kits/castle.js", 9689],
            ["js/world/art/kits/house.js", 6883],
            ["js/world/art/kits/landmarks.js", 16864],
            ["js/world/art/kits/town.js", 2627],
            ["js/world/avatar.js", 4952],
            ["js/world/effects.js", 14100],
            ["js/world/ground.js", 7444],
            ["js/world/squares.js", 3982],
            ["js/world/town3d.js", 10047],
            ["js/world/view.js", 10944],
        ],
    },
    {
        id: "body",
        label: "Body and shapes",
        detail: "MakeHuman base mesh, skeleton and sliders",
        files: [
            ["characters/human.bin", 1489413],
            ["characters/human.json", 111936],
        ],
    },
    {
        id: "skin",
        label: "Skin details",
        detail: "MakeHuman masks",
        files: [
            ["characters/masks/aureolae.jpg", 17232],
            ["characters/masks/crotch.jpg", 24810],
            ["characters/masks/ears.jpg", 18900],
            ["characters/masks/eyelids.jpg", 22684],
            ["characters/masks/fingernails.jpg", 18321],
            ["characters/masks/lips.jpg", 20552],
            ["characters/masks/toenails.jpg", 17589],
        ],
    },
    {
        id: "models",
        label: "Props and trees",
        detail: "KayKit Medieval Hexagon models",
        files: [
            ["models/kaykit/barrel.bin", 15552],
            ["models/kaykit/barrel.gltf", 3042],
            ["models/kaykit/building_well_blue.bin", 42340],
            ["models/kaykit/building_well_blue.gltf", 3083],
            ["models/kaykit/crate_A_big.bin", 7000],
            ["models/kaykit/crate_A_big.gltf", 3055],
            ["models/kaykit/crate_B_small.bin", 7000],
            ["models/kaykit/crate_B_small.gltf", 3059],
            ["models/kaykit/hexagons_medieval.png", 15783],
            ["models/kaykit/resource_lumber.bin", 11880],
            ["models/kaykit/resource_lumber.gltf", 3060],
            ["models/kaykit/resource_stone.bin", 11560],
            ["models/kaykit/resource_stone.gltf", 3061],
            ["models/kaykit/sack.bin", 3240],
            ["models/kaykit/sack.gltf", 3031],
            ["models/kaykit/target.bin", 7112],
            ["models/kaykit/target.gltf", 3016],
            ["models/kaykit/tent.bin", 6148],
            ["models/kaykit/tent.gltf", 3008],
            ["models/kaykit/tree_single_A.bin", 3340],
            ["models/kaykit/tree_single_A.gltf", 3053],
            ["models/kaykit/tree_single_B.bin", 7368],
            ["models/kaykit/tree_single_B.gltf", 3056],
            ["models/kaykit/weaponrack.bin", 2940],
            ["models/kaykit/weaponrack.gltf", 3027],
            ["models/kaykit/wheelbarrow.bin", 19016],
            ["models/kaykit/wheelbarrow.gltf", 3059],
        ],
    },
]);
