// Made by scripts/build-manifest.js (npm run build:manifest), don't edit: every file the game
// downloads before it starts, in groups, with each file's size in bytes (paths from the page), so
// the loading screen can show exactly how far it has got. test/manifest.test.js checks it's up to
// date.

export const MANIFEST = Object.freeze([
    {
        id: "engine",
        label: "3D engine",
        detail: "Three.js r186",
        files: [
            ["vendor/three-r186/addons/environments/RoomEnvironment.js", 2145],
            ["vendor/three-r186/addons/loaders/GLTFLoader.js", 45403],
            ["vendor/three-r186/addons/utils/BufferGeometryUtils.js", 13537],
            ["vendor/three-r186/addons/utils/SkeletonUtils.js", 4123],
            ["vendor/three-r186/three.core.min.js", 389591],
            ["vendor/three-r186/three.module.min.js", 376189],
        ],
    },
    {
        id: "code",
        label: "Game code",
        detail: "Pellagos",
        files: [
            ["js/app/camera.js", 4897],
            ["js/app/creator.js", 26373],
            ["js/app/doors.js", 8853],
            ["js/app/game.js", 105071],
            ["js/app/heroes.js", 5479],
            ["js/app/hud.js", 6643],
            ["js/app/icons.js", 6882],
            ["js/app/mapicons.js", 4448],
            ["js/app/minimap.js", 31296],
            ["js/app/pack.js", 6855],
            ["js/app/session.js", 2127],
            ["js/app/talk.js", 3448],
            ["js/app/wheel.js", 7477],
            ["js/app/worldmap.js", 21645],
            ["js/audio/dsp.js", 7151],
            ["js/audio/instruments.js", 2904],
            ["js/audio/samples.js", 3847],
            ["js/audio/score.js", 12468],
            ["js/audio/sound.js", 33678],
            ["js/audio/synth.js", 22171],
            ["js/audio/tavern.js", 11520],
            ["js/audio/worker.js", 958],
            ["js/characters/actions.js", 166556],
            ["js/characters/body.js", 8056],
            ["js/characters/character.js", 27203],
            ["js/characters/details.js", 6446],
            ["js/characters/drapes.js", 11123],
            ["js/characters/equipment.js", 19211],
            ["js/characters/face.js", 3403],
            ["js/characters/folk.js", 14507],
            ["js/characters/gait.js", 7667],
            ["js/characters/garments.js", 70865],
            ["js/characters/hair.js", 46985],
            ["js/characters/items.js", 25414],
            ["js/characters/kit.js", 829],
            ["js/characters/locomotion.js", 27100],
            ["js/characters/macro.js", 6921],
            ["js/characters/noise.js", 2651],
            ["js/characters/pack.js", 3799],
            ["js/characters/presets.js", 9955],
            ["js/characters/rig.js", 35687],
            ["js/characters/skin.js", 23743],
            ["js/characters/soldiers.js", 2073],
            ["js/core/battle.js", 69266],
            ["js/core/dialogue.js", 50198],
            ["js/core/explored.js", 3774],
            ["js/core/grid.js", 2643],
            ["js/core/host.js", 45271],
            ["js/core/insides.js", 31668],
            ["js/core/interiors.js", 15253],
            ["js/core/lore/gods.js", 4981],
            ["js/core/lore/taverns.js", 6121],
            ["js/core/names.js", 2625],
            ["js/core/noise.js", 2506],
            ["js/core/overworld.js", 38630],
            ["js/core/pathfinding.js", 8896],
            ["js/core/progress.js", 14660],
            ["js/core/random.js", 4020],
            ["js/core/roles.js", 7696],
            ["js/core/setpieces/exact.js", 2466],
            ["js/core/setpieces/pieces.js", 6410],
            ["js/core/setpieces/town.js", 37637],
            ["js/core/settlements.js", 7033],
            ["js/core/spells.js", 2177],
            ["js/core/variety.js", 1431],
            ["js/core/war/muster.js", 4479],
            ["js/core/war/news.js", 5103],
            ["js/core/war/peoples.js", 5272],
            ["js/core/war/roads.js", 4957],
            ["js/core/war/war.js", 44999],
            ["js/core/wilds.js", 10688],
            ["js/core/world.js", 9572],
            ["js/core/worldplan/plan.js", 6139],
            ["js/core/worldplan/queue.js", 1917],
            ["js/core/worldplan/races.js", 7862],
            ["js/core/worldplan/settle.js", 24018],
            ["js/core/worldplan/terrain.js", 18869],
            ["js/world/art/engine/atlas.js", 12475],
            ["js/world/art/engine/materials.js", 3031],
            ["js/world/art/engine/models.js", 2772],
            ["js/world/art/engine/paint-worker.js", 416],
            ["js/world/art/engine/painters.js", 21492],
            ["js/world/art/engine/solid.js", 22356],
            ["js/world/art/kits/castle.js", 9689],
            ["js/world/art/kits/emblems.js", 22704],
            ["js/world/art/kits/framing.js", 9824],
            ["js/world/art/kits/house.js", 37705],
            ["js/world/art/kits/landmarks.js", 26214],
            ["js/world/art/kits/props.js", 12544],
            ["js/world/art/kits/roofs.js", 11099],
            ["js/world/art/kits/signs.js", 16639],
            ["js/world/art/kits/town.js", 702],
            ["js/world/art/kits/trees.js", 70220],
            ["js/world/art/kits/wilds.js", 87314],
            ["js/world/avatar.js", 5015],
            ["js/world/banners3d.js", 9688],
            ["js/world/chunks3d.js", 25971],
            ["js/world/effects.js", 49108],
            ["js/world/ground.js", 17859],
            ["js/world/interiors3d.js", 71929],
            ["js/world/squares.js", 5968],
            ["js/world/town3d.js", 15909],
            ["js/world/view.js", 19454],
            ["js/world/wounds.js", 30915],
        ],
    },
    {
        id: "body",
        label: "Body and shapes",
        detail: "MakeHuman base mesh, skeleton and sliders",
        files: [
            ["characters/human.bin", 1500715],
            ["characters/human.json", 120520],
        ],
    },
    {
        id: "skin",
        label: "Skin details",
        detail: "MakeHuman masks",
        files: [
            ["characters/masks/aureolae.jpg", 17232],
            ["characters/masks/crotch.jpg", 24810],
            ["characters/masks/ears.jpg", 18900],
            ["characters/masks/eyelids.jpg", 22684],
            ["characters/masks/fingernails.jpg", 18321],
            ["characters/masks/lips.jpg", 20552],
            ["characters/masks/toenails.jpg", 17589],
        ],
    },
    {
        id: "fonts",
        label: "Lettering",
        detail: "UnifrakturMaguntia, for the tavern's signs",
        files: [
            ["fonts/UnifrakturMaguntia.woff2", 26512],
        ],
    },
]);
