// Every sound the game makes, described: what it is (`about`) and when the game plays it (`plays`),
// in groups, for the sound studio (sound-studio.html, js/lab/sound-studio.js), where each can be
// heard outside the game. Each of synth.js's SOUNDS, and each recorded sound with none made
// (sound.js RECORDED_ONLY), has its entry here (test/audio.test.js says so), so a sound added or
// changed is described with it; whether it's recorded, and by whom, is recorded.js's (made by npm
// run build:sounds), and what it's made of in code is synth.js's.

/** The groups, in the order the studio shows them. */
export const GROUPS = Object.freeze([
    "Footsteps",
    "Swings",
    "Hits",
    "Armour",
    "Drawing and putting away",
    "Launches",
    "Spells",
    "Fire spells",
    "Earth spells",
    "Air spells",
    "Water spells",
    "Healing spells",
    "Tome spells",
    "Bodies and doors",
    "Beasts",
    "Monsters",
    "Voices",
    "Folk at work",
    "The world",
    "Birds",
    "Town and farm",
    "Indoors",
    "Coins and trade",
    "In hand",
    "The interface",
    "Cues",
]);

/** Each sound (a synth.js SOUNDS or sound.js RECORDED_ONLY name): { group, label, about, plays }. */
export const CATALOG = Object.freeze({
    // Footsteps (sound.js step: audio/footing.js picks the footing)
    stepGrass: { group: "Footsteps", label: "Grass", about: "A footfall on grass: soft-soled boots brushing through the blades, a muffled thud under them.", plays: "Each foot landing on grass, meadow, farmland's pasture and most land out in the world." },
    stepDirt: { group: "Footsteps", label: "Dirt", about: "A footfall on packed earth: a dull thud and a little grit.", plays: "Each foot landing on a road, a track, or ploughed soil." },
    stepStone: { group: "Footsteps", label: "Stone", about: "A footfall on stone: a soft-soled thud, the stone's short knock and a scrape of grit.", plays: "Each foot landing on cobbles, a courtyard's flags, or a stone bridge's deck." },
    stepWood: { group: "Footsteps", label: "Wood", about: "A footfall on boards: a hollow thud with the boards' low ring.", plays: "Each foot landing on a floor's boards, a wooden bridge or a jetty; the treads going up and down stairs; a guard's stamp to attention." },
    stepSand: { group: "Footsteps", label: "Sand", about: "A footfall on wet sand: a soft, damp crunch.", plays: "Each foot landing on a beach, or a road through sand." },
    stepSnow: { group: "Footsteps", label: "Snow", about: "A footfall in snow: snow packing down underfoot, a squeaky crunch.", plays: "Each foot landing in the snow and the tundra, and anywhere above 225 m." },
    stepGravel: { group: "Footsteps", label: "Scree", about: "A footfall on loose stones: a rattling crunch.", plays: "Each foot landing on mountains, badlands and the volcano's ash, and anywhere from 175 m up to the snow." },
    stepMud: { group: "Footsteps", label: "Mud", about: "A footfall in mud: a wet slap as the foot sinks, a suck as it pulls free.", plays: "Each foot landing in the marsh, or on ploughed soil there." },
    stepLeaves: { group: "Footsteps", label: "Leaf litter", about: "A footfall in dry leaves: a crackling rustle.", plays: "Each foot landing in the woods, the dark wood, the elves' wood and the jungle." },
    stepWater: { group: "Footsteps", label: "Wading", about: "Wading through shallow water: a splash and a slosh round the legs.", plays: "Each foot landing in a river's ford, a stream, or the shallows." },
    skitter: { group: "Footsteps", label: "Spider's legs", about: "Many hard legs ticking down one after another.", plays: "A cave spider's or a scorpion's footfalls, whatever the ground." },
    squelch: { group: "Footsteps", label: "Slime", about: "A wet belly flopping along, with a few bubbles.", plays: "A slime's or a magma slime's footfalls; and a bog frog's webbed feet, higher and softer." },
    slither: { group: "Footsteps", label: "Serpent", about: "Scales sliding over the ground.", plays: "A snake's footfalls, whatever the ground." },

    // Swings (sound.js attack: timed so each is loudest as the blow lands)
    swingSword: { group: "Swings", label: "Sword", about: "A sabre cutting the air edge first: short and bright.", plays: "Every sword blow, loudest as it lands." },
    swingCleaver: { group: "Swings", label: "Cleaver", about: "The same sabre's broader cuts: a heavier swish.", plays: "Every cleaver blow, loudest as it lands." },
    swingStaff: { group: "Swings", label: "Staff", about: "A bamboo staff whooshing round.", plays: "Every quarterstaff blow, loudest as it lands." },
    swingHammer: { group: "Swings", label: "War hammer", about: "The sabre swung flat: a low, slow whomp.", plays: "Every war hammer, greatsword and battle axe blow (they swing alike), loudest as it lands." },
    swingPunch: { group: "Swings", label: "Punch", about: "A sleeve whooshing as the fist's thrown.", plays: "Every punch, loudest as it lands." },
    swingKick: { group: "Swings", label: "Kick", about: "A fighter's quick dodge and swing: a short swish of cloth.", plays: "Every kick, loudest as it lands." },
    swingWand: { group: "Swings", label: "Wand", about: "A thin bamboo stick flicked through the air.", plays: "Every flick of a wand, as its bolt's let go." },

    // Hits (sound.js hit: by the blow's reaction, core/weapons.js)
    slash: { group: "Hits", label: "Slash", about: "A blade biting: a sharp, wet slap (a wet towel on a bare back, its brighter half).", plays: "A sword's cut landing on anyone." },
    hack: { group: "Hits", label: "Hack", about: "A heavy blade chopping in: a deeper, wet slap.", plays: "A cleaver's blow landing." },
    cleave: { group: "Hits", label: "Cleave", about: "A long blade sweeping through: a lower, longer slash, ringing.", plays: "A greatsword's cut landing." },
    chop: { group: "Hits", label: "Chop", about: "An axe's broad blade driven in: deeper than a hack, more thud than ring.", plays: "A battle axe's blow landing." },
    strike: { group: "Hits", label: "Strike", about: "A wooden staff cracking on a body.", plays: "A staff's blow landing." },
    crush: { group: "Hits", label: "Crush", about: "A heavy blunt blow: a deep, meaty thud.", plays: "A war hammer's blow landing." },
    block: { group: "Hits", label: "Block", about: "A blow caught on wood: a hard knock (a blade on an ash spear shaft).", plays: "A blow taken on a shield (a blade's rings on it instead: Clash)." },
    clash: { group: "Hits", label: "Clash", about: "Steel ringing on steel (a sabre on a sword).", plays: "A sword's or a cleaver's blow, or a skeleton's rusty sword, caught on a shield's iron." },
    pierce: { group: "Hits", label: "Pierce", about: "An arrow thunking into a body.", plays: "An arrow striking anyone." },
    punch: { group: "Hits", label: "Punch", about: "A fist landing: a meaty thud (fists on a punching bag).", plays: "A punch landing." },
    kick: { group: "Hits", label: "Kick", about: "A boot driving in: a heavy thud.", plays: "A kick landing." },
    arcane: { group: "Hits", label: "Arcane", about: "A Nepalese hand bell's ping, a burst of whoosh, and a cymbal's shimmer or scrape.", plays: "Magic striking without a landing of its own (a creature's bolt, a spell turned back by Reflect), and a spell caught on a spellward." },
    fire: { group: "Hits", label: "Fire", about: "A short fwump of flame, with a sizzle or crackle.", plays: "Fire striking anyone but as a fire spell lands (that has its own): a creature's breath or lava, burning ground." },

    // Armour (sound.js ARMOUR: what's worn over the chest, game.js armourOf)
    hitMail: { group: "Armour", label: "Blow on mail", about: "Mail's rings shaken by a blow: a short, bright jangle.", plays: "Under a weapon's or a fist's blow landing on anyone in a mail shirt." },
    hitPlate: { group: "Armour", label: "Blow on plate", about: "Steel plate struck: a hard, flat clank.", plays: "Under a blow landing on anyone in a breastplate." },
    hitLeather: { group: "Armour", label: "Blow on leather", about: "Thick leather struck: a dull slap.", plays: "Under a blow landing on anyone in a leather jerkin or a hide vest." },
    mailJingle: { group: "Armour", label: "Mail on the move", about: "Mail's rings shifting with a step.", plays: "With each step of anyone in a mail shirt, a little under the footstep." },
    plateClank: { group: "Armour", label: "Plate on the move", about: "Plates knocking together with a step (a knight walking in armour).", plays: "With each step of anyone in a breastplate, a little under the footstep." },
    clothRustle: { group: "Armour", label: "Leather on the run", about: "A jacket swishing.", plays: "With each running step of anyone in a leather jerkin or a hide vest." },

    // Drawing and putting away (game.js #draw)
    unsheathe: { group: "Drawing and putting away", label: "Draw a sword", about: "A blade drawn from a leather sheath: a quiet scrape, no film's ring.", plays: "Drawing a sword (after a shield's slung off the back)." },
    sheathe: { group: "Drawing and putting away", label: "Sheathe a sword", about: "A blade slid home into leather.", plays: "Putting a sword away." },
    unsling: { group: "Drawing and putting away", label: "Unsling", about: "Something taken off the back, or put back there: a strap's creak and a wooden knock.", plays: "Drawing or putting away a staff, a hammer, a cleaver, a bow or a wand." },
    shieldSling: { group: "Drawing and putting away", label: "Shield slung", about: "A shield's strap creaking and its boards' thud as it's slung.", plays: "A shield slung off the back before a weapon's drawn, or onto it after it's put away." },
    grimoire: { group: "Drawing and putting away", label: "Grimoire", about: "A heavy book handled: its cover and pages.", plays: "Drawing or putting away a grimoire." },
    knuckles: { group: "Drawing and putting away", label: "Fists up", about: "Hands closing into fists: soft leather creaking.", plays: "Raising the fists, or the boots' kicks, to fight." },

    // Launches (sound.js launch)
    arrowQuiver: { group: "Launches", label: "Arrow from the quiver", about: "An arrow drawn from a leather quiver.", plays: "A bow's shot starting." },
    bowDraw: { group: "Launches", label: "Bow drawn", about: "An English longbow drawn: the string and the wood creaking.", plays: "A bow's shot, as it's drawn back." },
    arrow: { group: "Launches", label: "Arrow loosed", about: "An English longbow loosed: the string's thrum and the arrow leaving.", plays: "An arrow loosed from a bow." },
    bolt: { group: "Launches", label: "Bolt", about: "A whoosh carrying a bowed cymbal's shimmer: magic in flight.", plays: "Casting Stun, Hold and the other spells cast at an enemy without a school; Poison flying; creatures' venom, webs, curses, wails and the like flying." },
    fireball: { group: "Launches", label: "Fireball", about: "A ball of fire flying: a whoosh (a pencil swept over paper) over flame's arching roar and crackle.", plays: "Burn's, Fireball's and Burstflame's fire flying; a creature's lava or flame." },
    stoneShot: { group: "Launches", label: "Stone", about: "A heavy stone whooshing through the air, a little grit as it's thrown.", plays: "Stone Crush's stone flying." },
    waterbolt: { group: "Launches", label: "Water", about: "Water flying: a whoosh over a sustained splash.", plays: "Blister's and Waterbolt's water flying." },

    // Spells
    castHeal: { group: "Spells", label: "Casting a heal (made)", about: "A rising shimmer, made in code.", plays: "In place of the healing casts' recordings, until they're downloaded." },
    healed: { group: "Spells", label: "Healed", about: "A warm swell, made in code.", plays: "Healing that isn't a spell's landing (a priest's blessing, a potion); and in place of the healing landings' recordings, until they're downloaded." },
    stun: { group: "Spells", label: "Stunned", about: "A zap and a dizzy warble.", plays: "Someone stunned." },

    // Fire spells (sound.js spellSounds: by the spell's tier; a cast swells to its release, loudest as it's let go)
    castFireLow: { group: "Fire spells", label: "Casting, tiers 1–2", about: "A small flame gathering: a match's flare, or a flame's whoosh drawn in backwards, with a little crackle, swelling to the release.", plays: "Casting Burn or Fireball, swelling until it's let go." },
    impactFireLow: { group: "Fire spells", label: "Landing, tiers 1–2", about: "A fire catching: a fwoomp of flame, and crackle after.", plays: "Burn or Fireball landing on whoever it's cast at." },
    castFireMid: { group: "Fire spells", label: "Casting, tiers 3–5", about: "Fire gathering: flames' whooshes drawn in over a wildfire's swelling roar and crackle.", plays: "Casting Burstflame, Immolate or Flamefill, swelling until it's let go." },
    impactFireMid: { group: "Fire spells", label: "Landing, tiers 3–5", about: "A burst of fire, its roar, and a crackling tail.", plays: "Burstflame, Immolate or Flamefill landing on whoever it's cast at." },
    castFireHigh: { group: "Fire spells", label: "Casting, tiers 6–7", about: "A wildfire's roar building from far down, dense crackle, and a flame's whoosh drawn in to the release.", plays: "Casting Inferno or Hellfire, swelling until it's let go." },
    impactFireHigh: { group: "Fire spells", label: "Landing, tiers 6–7", about: "A great burst of fire with a wildfire's roar under it and a long, crackling tail.", plays: "Inferno or Hellfire landing on whoever it's cast at." },

    // Earth spells (sound.js spellSounds: by the spell's tier; a cast swells to its release, loudest as it's let go)
    castEarthLow: { group: "Earth spells", label: "Casting, tiers 1–2", about: "A stone slab grinding, swelling, with stone-on-stone grit.", plays: "Casting Rumble or Stone Crush, swelling until it's let go." },
    impactEarthLow: { group: "Earth spells", label: "Landing, tiers 1–2", about: "A rock knocking onto a pile, with a short clatter.", plays: "Rumble or Stone Crush landing on whoever it's cast at." },
    castEarthMid: { group: "Earth spells", label: "Casting, tiers 3–5", about: "Heavier grinding, and rubble beginning to slide.", plays: "Casting Shatterstone, Engulf or Earthquake, swelling until it's let go." },
    impactEarthMid: { group: "Earth spells", label: "Landing, tiers 3–5", about: "A boulder crashing down, and a rock's knock.", plays: "Shatterstone, Engulf or Earthquake landing on whoever it's cast at." },
    castEarthHigh: { group: "Earth spells", label: "Casting, tiers 6–7", about: "Two stones grinding, a rockfall and a boulder's rumble, all building.", plays: "Casting Acidify or Disintegrate, swelling until it's let go." },
    impactEarthHigh: { group: "Earth spells", label: "Landing, tiers 6–7", about: "A boulder and a rockfall, with the ground's deep rumble under them (thunder, far down).", plays: "Acidify or Disintegrate landing on whoever it's cast at." },

    // Air spells (sound.js spellSounds: by the spell's tier; a cast swells to its release, loudest as it's let go)
    castAirLow: { group: "Air spells", label: "Casting, tiers 1–2", about: "A gust of wind swelling, a whoosh drawn in.", plays: "Casting Hurt or Dustgust, swelling until it's let go." },
    impactAirLow: { group: "Air spells", label: "Landing, tiers 1–2", about: "A cutting whoosh; some with grit in it (Dustgust's).", plays: "Hurt or Dustgust landing on whoever it's cast at." },
    castAirMid: { group: "Air spells", label: "Casting, tiers 3–5", about: "Electricity gathering: a Tesla coil's sizzle and sparks crowding in.", plays: "Casting Shockbolt, Lightning or Thunderbolt, swelling until it's let go." },
    impactAirMid: { group: "Air spells", label: "Landing, tiers 3–5", about: "Lightning striking: its crack, sparks spitting, and thunder or a sizzle.", plays: "Shockbolt, Lightning or Thunderbolt landing on whoever it's cast at." },
    castAirHigh: { group: "Air spells", label: "Casting, tiers 6–7", about: "Wind roaring up round lightning's crackling build, a coil's buzz and sparks.", plays: "Casting Tornado or Ionize, swelling until it's let go." },
    impactAirHigh: { group: "Air spells", label: "Landing, tiers 6–7", about: "A strike, thunder rolling, a gust and sparks.", plays: "Tornado or Ionize landing on whoever it's cast at." },
    shockbolt: { group: "Air spells", label: "Shockbolt", about: "A spark's crack, then a Tesla coil's buzz.", plays: "Shockbolt striking, in place of the lightning's landing." },

    // Water spells (sound.js spellSounds: by the spell's tier; a cast swells to its release, loudest as it's let go)
    castWaterLow: { group: "Water spells", label: "Casting, tiers 1–2", about: "Water bubbling, and a wash drawn in.", plays: "Casting Blister or Waterbolt, swelling until it's let go." },
    impactWaterLow: { group: "Water spells", label: "Landing, tiers 1–2", about: "A splash into a lake, with a scald's sizzle.", plays: "Blister or Waterbolt landing on whoever it's cast at." },
    castWaterMid: { group: "Water spells", label: "Casting, tiers 3–5", about: "Water coming to the boil, steam hissing up, and an ice tick drawn in.", plays: "Casting Steamblast, Bloodboil or Iceblade, swelling until it's let go." },
    impactWaterMid: { group: "Water spells", label: "Landing, tiers 3–5", about: "Steam bursting over a plunge, boiling water, or ice cracking with a hiss.", plays: "Steamblast, Bloodboil or Iceblade landing on whoever it's cast at." },
    castWaterHigh: { group: "Water spells", label: "Casting, tiers 6–7", about: "A mud pot's deep bubbling and hiss, thin ice ringing, and ice building to the release.", plays: "Casting Putrify or Absolute Zero, swelling until it's let go." },
    impactWaterHigh: { group: "Water spells", label: "Landing, tiers 6–7", about: "Freezing and festering: ice cracking over a mud pot's bubbling, or foul water boiling under a burst of steam.", plays: "Putrify or Absolute Zero landing on whoever it's cast at." },

    // Healing spells (sound.js spellSounds: by the spell's tier; a cast swells to its release, loudest as it's let go)
    castHealingLow: { group: "Healing spells", label: "Casting, tiers 1–2", about: "A singing bowl's rim swelling under a rising shimmer of chimes (a mark tree).", plays: "Casting Vigor or Mend Wounds, swelling until it's let go; and casting a tome's spell on a friend or yourself." },
    impactHealingLow: { group: "Healing spells", label: "Landing, tiers 1–2", about: "One warm hand chime, and a falling shimmer.", plays: "Vigor or Mend Wounds landing on whoever's healed." },
    castHealingMid: { group: "Healing spells", label: "Casting, tiers 3–4", about: "The bowl and the rising shimmer, with a hand chime drawn in backwards.", plays: "Casting Detraumatize or Renewal, swelling until it's let go." },
    impactHealingMid: { group: "Healing spells", label: "Landing, tiers 3–4", about: "A chord of three hand chimes (or the bowl with two).", plays: "Detraumatize or Renewal landing on whoever's healed." },
    castHealingHigh: { group: "Healing spells", label: "Casting, tier 5", about: "A chord of chimes drawn in backwards, a tubular bell under it.", plays: "Casting Astral Heal, swelling until it's let go." },
    impactHealingHigh: { group: "Healing spells", label: "Landing, tier 5", about: "A tubular bell under the chord, the bowl and the chimes falling.", plays: "Astral Heal landing on whoever's healed." },

    // Tome spells (sound.js spellSounds: what each does, as it lands)
    buff: { group: "Tome spells", label: "Strength given", about: "A shimmer of chimes sweeping up to a glockenspiel's note, with a triangle's roll or a cymbal's swell.", plays: "Embolden, Swole, Surge, Dodge or Levitate landing." },
    ward: { group: "Tome spells", label: "A ward raised", about: "A rubbed wine glass singing over a bowed cymbal.", plays: "A Resist spell, Reflect or Inertial Barrier landing." },
    cure: { group: "Tome spells", label: "Cured", about: "A singing bowl struck softly, a glockenspiel's or a hand bell's note, and a faint falling shimmer.", plays: "A cure (Cure Poison, Cure Sickness, Lift Curse, Quench, Staunch, Unbind) or Pacify landing." },
    hex: { group: "Tome spells", label: "Hexed", about: "Whispering voices over a bowed brake drum, slowed, and a scraped gong.", plays: "Poison or Vampirism landing." },
    fear: { group: "Tome spells", label: "Fear", about: "A slow whoosh, a scraped gong, bowed metal rising, and a whisper.", plays: "Fear landing." },
    teleportOut: { group: "Tome spells", label: "Carried off", about: "A whoosh and a cymbal's swell drawn up into a bottle's uncorking pop, then gone.", plays: "Anyone carried off by magic (Teleport, Word of Recall, Wizard's Walk, a summons, a Scroll of Safety, a guild's portal), as they go; Invisibility landing, hushed." },
    teleportIn: { group: "Tome spells", label: "Arriving", about: "The pop first, then the whoosh blowing out, and a faint shimmer.", plays: "Anyone carried by magic arriving, a guild's portal's too." },
    summon: { group: "Tome spells", label: "Summoned", about: "A scraped gong or a bowed cymbal swelling in, then a rock's knock or a boulder's crash arriving in a gust of dust.", plays: "Summon, Attraction or Zombify landing." },
    polymorph: { group: "Tome spells", label: "Polymorph", about: "A flexatone's warped warble with a shimmer of chimes and a bowed cymbal.", plays: "Polymorph landing." },
    lightSpell: { group: "Tome spells", label: "Light", about: "A match flaring (without its strike), a glockenspiel's note, and a faint triangle roll.", plays: "Light lit over the shoulder, or put out." },
    fizzle: { group: "Tome spells", label: "Fizzle", about: "A match that won't catch, and a puff of steam.", plays: "A spell broken off before it's let go (its caster stunned or knocked down), or a Scroll of Safety with nowhere to take you." },
    spellCircle: { group: "Tome spells", label: "Scroll of Safety", about: "A cymbal rolled up to a crescendo under a bowed cymbal, a climbing shimmer of chimes and a triangle's roll.", plays: "Reading a Scroll of Safety: swelling as its circle grows, loudest as you're carried off." },

    // Bodies and doors
    fall: { group: "Bodies and doors", label: "A body falling", about: "A body hitting the ground (a person falling on a wooden floor), from its first heavy contact.", plays: "Anyone falling, dead or knocked down, as they hit the ground." },
    fallArmoured: { group: "Bodies and doors", label: "An armoured body falling", about: "A body falling, with mail rattling down after it.", plays: "Anyone in mail or plate falling, as they hit the ground." },
    dropWeapon: { group: "Bodies and doors", label: "A weapon dropped", about: "Iron clattering onto a hard floor.", plays: "Anyone armed falling dead: what they fought with, just after they hit the ground." },
    door: { group: "Bodies and doors", label: "A door", about: "An old wooden door: a creak or the latch, then it shutting. kyles's rattly old door, on Freesound.", plays: "Anyone going through a house's, a tavern's, a smithy's or a guild's door on the player's side of it." },
    deathThudSmall: { group: "Bodies and doors", label: "A small body falling", about: "A small body dropping onto leaves.", plays: "A small creature (a rat, a porcupine, an adder, a spider, a scorpion, a frog) falling dead, as it hits the ground." },
    deathThudMid: { group: "Bodies and doors", label: "A beast falling", about: "A body falling to the ground, on leaves or a carpet.", plays: "A wolf, a dire wolf, a black shuck, a hyena, a boar, a puma or a shadow stalker falling dead, as it hits the ground." },
    deathThudBig: { group: "Bodies and doors", label: "A great beast falling", about: "A heavy body falling on dirt, slowed.", plays: "A bear, a crocodile, a rock tusker, a wyvern or a dragon falling dead, as it hits the ground." },
    doorHeavy: { group: "Bodies and doors", label: "A heavy door", about: "A big wooden door swinging open and shut with a deep thud: Denis Chapon's, and LampEight's theatre door.", plays: "Going in or out of a keep, a castle's undercroft, a temple, a town hall or a watchtower." },
    gate: { group: "Bodies and doors", label: "An iron gate", about: "A cemetery's iron gate rattling open and clanging shut: launemax's.", plays: "Going in or out of a ruined keep's great hall." },
    trapdoor: { group: "Bodies and doors", label: "A trapdoor", about: "A wooden shutter opened and slammed shut (kyles's), standing in for a hatch.", plays: "Going down into a crypt, or up out of one." },
    stairs: { group: "Bodies and doors", label: "Wooden stairs", about: "Three or four creaking treads of an old wooden stair, no feet between: NachtmahrTV's, played a little quicker.", plays: "Anyone going up or down wooden stairs (a tavern's), under their footsteps." },

    // Beasts (sound.js CREATURE_VOICES: each creature its family's, at its own pitch)
    wolfCall: { group: "Beasts", label: "Wolf calling", about: "A lone wolf's howl rising and falling, a creek echoing it: an NPS acoustician's in Wrangell–St. Elias, and one from Denali.", plays: "A wolf (a dire wolf lower, a black shuck lower still, a hyena a little higher) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    wolfAttack: { group: "Beasts", label: "Wolf attacking", about: "A dog's short growling snarl.", plays: "A wolf (a dire wolf lower, a black shuck lower still, a hyena a little higher) striking, loudest as its blow lands." },
    wolfHurt: { group: "Beasts", label: "Wolf hurt", about: "A dog's sharp yelp.", plays: "A wolf (a dire wolf lower, a black shuck lower still, a hyena a little higher) struck, no oftener than every 0.7 seconds." },
    wolfDeath: { group: "Beasts", label: "Wolf dying", about: "A long yelp, or a whimper fading.", plays: "A wolf (a dire wolf lower, a black shuck lower still, a hyena a little higher) dying." },
    bearCall: { group: "Beasts", label: "Bear calling", about: "A grizzly huffing, popping its jaws and growling (Yellowstone's).", plays: "A brown bear setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    bearAttack: { group: "Beasts", label: "Bear attacking", about: "A bear's roaring growl (the US Fish and Wildlife Service's, and Yellowstone's).", plays: "A brown bear striking, loudest as its blow lands." },
    bearHurt: { group: "Beasts", label: "Bear hurt", about: "A grizzly's short huff or jaw pop.", plays: "A brown bear struck, no oftener than every 0.7 seconds." },
    bearDeath: { group: "Beasts", label: "Bear dying", about: "A grizzly's growl dying away.", plays: "A brown bear dying." },
    boarCall: { group: "Beasts", label: "Boar calling", about: "A wild boar grunting in a German wood.", plays: "A wild boar (a rock tusker lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    boarAttack: { group: "Beasts", label: "Boar attacking", about: "Wild pigs squealing and grunting (Florida's).", plays: "A wild boar (a rock tusker lower) striking, loudest as its blow lands." },
    boarHurt: { group: "Beasts", label: "Boar hurt", about: "A wild pig's squeal.", plays: "A wild boar (a rock tusker lower) struck, no oftener than every 0.7 seconds." },
    boarDeath: { group: "Beasts", label: "Boar dying", about: "A wild pig's long squeal, fading.", plays: "A wild boar (a rock tusker lower) dying." },
    bigCatCall: { group: "Beasts", label: "Big cat calling", about: "An angry cat's growling yowl, slowed to a big cat's.", plays: "A puma (a shadow stalker lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    bigCatAttack: { group: "Beasts", label: "Big cat attacking", about: "A cat's hiss and spit, slowed.", plays: "A puma (a shadow stalker lower) striking, loudest as its blow lands." },
    bigCatHurt: { group: "Beasts", label: "Big cat hurt", about: "A cat's yowl, slowed.", plays: "A puma (a shadow stalker lower) struck, no oftener than every 0.7 seconds." },
    bigCatDeath: { group: "Beasts", label: "Big cat dying", about: "A cat's long growl, slowed further, dying away.", plays: "A puma (a shadow stalker lower) dying." },
    ratCall: { group: "Beasts", label: "Rat calling", about: "A pet rat squeaking, close.", plays: "A giant rat (a porcupine lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    ratAttack: { group: "Beasts", label: "Rat attacking", about: "A rat's sharp squeak.", plays: "A giant rat (a porcupine lower) striking, loudest as its blow lands." },
    ratHurt: { group: "Beasts", label: "Rat hurt", about: "A rat's shriek.", plays: "A giant rat (a porcupine lower) struck, no oftener than every 0.7 seconds." },
    ratDeath: { group: "Beasts", label: "Rat dying", about: "A rat's squeak, slowed, fading.", plays: "A giant rat (a porcupine lower) dying." },
    snakeCall: { group: "Beasts", label: "Snake calling", about: "A snake's long hiss (a pet snake's, a cobra's in a backyard).", plays: "An adder setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    snakeAttack: { group: "Beasts", label: "Snake attacking", about: "A cobra's snarl, a kingsnake lunging.", plays: "An adder striking, loudest as its blow lands." },
    snakeHurt: { group: "Beasts", label: "Snake hurt", about: "A short, sharp hiss.", plays: "An adder struck, no oftener than every 0.7 seconds." },
    snakeDeath: { group: "Beasts", label: "Snake dying", about: "A hiss trailing away.", plays: "An adder dying." },
    crocCall: { group: "Beasts", label: "Crocodile calling", about: "An alligator's deep, rumbling growl.", plays: "A marsh crocodile setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    crocAttack: { group: "Beasts", label: "Crocodile attacking", about: "A snake's hiss, slowed, over an alligator's growl.", plays: "A marsh crocodile striking, loudest as its blow lands." },
    crocHurt: { group: "Beasts", label: "Crocodile hurt", about: "A young caiman's distress grunt, slowed.", plays: "A marsh crocodile struck, no oftener than every 0.7 seconds." },
    crocDeath: { group: "Beasts", label: "Crocodile dying", about: "An alligator's growl, slowed, dying away.", plays: "A marsh crocodile dying." },
    frogCall: { group: "Beasts", label: "Frog calling", about: "A green frog's croak slowed to a giant's, and a pig frog's grunt (the Everglades').", plays: "A bog frog setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    frogAttack: { group: "Beasts", label: "Frog attacking", about: "A short, deep croak.", plays: "A bog frog striking, loudest as its blow lands." },
    frogHurt: { group: "Beasts", label: "Frog hurt", about: "A common toad's distress cry.", plays: "A bog frog struck, no oftener than every 0.7 seconds." },
    frogDeath: { group: "Beasts", label: "Frog dying", about: "A deep croak, slowed further, fading.", plays: "A bog frog dying." },
    batsCall: { group: "Beasts", label: "Bats calling", about: "A bat's high chirps, close.", plays: "A bat swarm setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    batsAttack: { group: "Beasts", label: "Bats attacking", about: "Chirps over pigeons' wings fluttering.", plays: "A bat swarm striking, loudest as its blow lands." },
    batsHurt: { group: "Beasts", label: "Bats hurt", about: "A bat's squeak.", plays: "A bat swarm struck, no oftener than every 0.7 seconds." },
    batsDeath: { group: "Beasts", label: "Bats dying", about: "Chirps slowed, a flutter fading.", plays: "A bat swarm dying." },
    smallWings: { group: "Beasts", label: "Bats' wings", about: "Pigeons taking off: a flurry of wingbeats.", plays: "Under a bat swarm's call, attack and death." },
    spiderCall: { group: "Beasts", label: "Spider calling", about: "A grasshopper's wing snaps: a dry chitter.", plays: "A cave spider (a sand scorpion lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    spiderAttack: { group: "Beasts", label: "Spider attacking", about: "A hissing cockroach's hiss, close.", plays: "A cave spider (a sand scorpion lower) striking, loudest as its blow lands." },
    spiderHurt: { group: "Beasts", label: "Spider hurt", about: "A short hiss.", plays: "A cave spider (a sand scorpion lower) struck, no oftener than every 0.7 seconds." },
    spiderDeath: { group: "Beasts", label: "Spider dying", about: "A hiss, slowed, and clicks.", plays: "A cave spider (a sand scorpion lower) dying." },

    // Monsters
    slimeCall: { group: "Monsters", label: "Slime calling", about: "Real slime squelching and squishing.", plays: "A green slime (a magma slime lower, sizzling) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    slimeAttack: { group: "Monsters", label: "Slime attacking", about: "A wet slap of slime.", plays: "A green slime (a magma slime lower, sizzling) striking, loudest as its blow lands." },
    slimeHurt: { group: "Monsters", label: "Slime hurt", about: "A squelch.", plays: "A green slime (a magma slime lower, sizzling) struck, no oftener than every 0.7 seconds." },
    slimeDeath: { group: "Monsters", label: "Slime dying", about: "Slime collapsing, squishing to rest.", plays: "A green slime (a magma slime lower, sizzling) dying." },
    slimeSizzle: { group: "Monsters", label: "Magma slime's sizzle", about: "Sausages sizzling in a pan, the low end taken off.", plays: "Under a magma slime's call, attack and death." },
    skeletonCall: { group: "Monsters", label: "Skeleton calling", about: "Bones rattling.", plays: "A skeleton setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    skeletonAttack: { group: "Monsters", label: "Skeleton attacking", about: "A sharp rattle of bones.", plays: "A skeleton striking, loudest as its blow lands: now and then." },
    skeletonHurt: { group: "Monsters", label: "Skeleton hurt", about: "Bones knocked.", plays: "A skeleton struck, no oftener than every 0.7 seconds." },
    skeletonDeath: { group: "Monsters", label: "Skeleton dying", about: "Bones falling to the ground in a heap.", plays: "A skeleton dying." },
    ghostCall: { group: "Monsters", label: "Ghost calling", about: "Whispering voices.", plays: "A restless ghost (a will-o'-wisp higher, a wraith lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    ghostAttack: { group: "Monsters", label: "Ghost attacking", about: "A ghostly moan (a voice actor's).", plays: "A restless ghost (a will-o'-wisp higher, a wraith lower) striking, loudest as its blow lands." },
    ghostHurt: { group: "Monsters", label: "Ghost hurt", about: "A burst of whispers, or a moan.", plays: "A restless ghost (a will-o'-wisp higher, a wraith lower) struck, no oftener than every 0.7 seconds." },
    ghostDeath: { group: "Monsters", label: "Ghost dying", about: "A long moan fading away.", plays: "A restless ghost (a will-o'-wisp higher, a wraith lower) dying." },
    wightCall: { group: "Monsters", label: "Wight lord calling", about: "An undead moan, slowed.", plays: "The wight lord setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    wightAttack: { group: "Monsters", label: "Wight lord attacking", about: "A zombie's snarl, slowed.", plays: "The wight lord striking, loudest as its blow lands: now and then." },
    wightHurt: { group: "Monsters", label: "Wight lord hurt", about: "A zombie's groan, slowed.", plays: "The wight lord struck, no oftener than every 0.7 seconds." },
    wightDeath: { group: "Monsters", label: "Wight lord dying", about: "A long undead moan, slowed further.", plays: "The wight lord dying." },
    treantCall: { group: "Monsters", label: "Treant calling", about: "A tree creaking in the wind (in Patagonia), and old floorboards.", plays: "A blighted treant setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    treantAttack: { group: "Monsters", label: "Treant attacking", about: "Old wood creaking, slowed.", plays: "A blighted treant striking, loudest as its blow lands." },
    treantHurt: { group: "Monsters", label: "Treant hurt", about: "Wood cracking.", plays: "A blighted treant struck, no oftener than every 0.7 seconds." },
    treantDeath: { group: "Monsters", label: "Treant dying", about: "A great tree splintering and crashing down.", plays: "A blighted treant dying." },
    dragonCall: { group: "Monsters", label: "Dragon calling", about: "A lion's growl and an alligator's, slowed and layered.", plays: "A dragon (a wyvern higher) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    dragonAttack: { group: "Monsters", label: "Dragon attacking", about: "Bison bellowing with a lion, slowed.", plays: "A dragon (a wyvern higher) striking, loudest as its blow lands." },
    dragonHurt: { group: "Monsters", label: "Dragon hurt", about: "A bison's short bellow, slowed.", plays: "A dragon (a wyvern higher) struck, no oftener than every 0.7 seconds." },
    dragonDeath: { group: "Monsters", label: "Dragon dying", about: "A bison's long bellow with a lion's growl, dying away.", plays: "A dragon (a wyvern higher) dying." },
    dragonBreath: { group: "Monsters", label: "Dragon's fire", about: "Fire whooshing up (diesel thrown on a bonfire), and a bonfire catching.", plays: "A dragon breathing fire (the made fireball in its place until it's downloaded)." },
    wingbeat: { group: "Monsters", label: "Great wings", about: "Huge wings flapping (bed sheets, whipped).", plays: "A dragon or a wyvern beating its wings in the air near the player, and flaring as it comes down to land." },
    goblinCall: { group: "Monsters", label: "Goblin calling", about: "A goblin's cackling laugh (voice actors').", plays: "A goblin raider (a boggart lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    goblinAttack: { group: "Monsters", label: "Goblin attacking", about: "A man's growl, sped up.", plays: "A goblin raider (a boggart lower) striking, loudest as its blow lands: now and then." },
    goblinHurt: { group: "Monsters", label: "Goblin hurt", about: "A pain grunt, sped up.", plays: "A goblin raider (a boggart lower) struck, no oftener than every 0.7 seconds." },
    goblinDeath: { group: "Monsters", label: "Goblin dying", about: "A goblin's death cry.", plays: "A goblin raider (a boggart lower) dying." },
    trollCall: { group: "Monsters", label: "Troll calling", about: "Men's growls slowed, and a bison's bellow.", plays: "A troll (an ogre a little higher, a frost troll lower) setting on someone, and now and then as it goes about its business; heard up to 50 metres off." },
    trollAttack: { group: "Monsters", label: "Troll attacking", about: "A deep fight grunt, slowed.", plays: "A troll (an ogre a little higher, a frost troll lower) striking, loudest as its blow lands: now and then." },
    trollHurt: { group: "Monsters", label: "Troll hurt", about: "A deep pain grunt, slowed.", plays: "A troll (an ogre a little higher, a frost troll lower) struck, no oftener than every 0.7 seconds." },
    trollDeath: { group: "Monsters", label: "Troll dying", about: "A bison's bellow, or a man's death grunt, slowed.", plays: "A troll (an ogre a little higher, a frost troll lower) dying." },

    // Voices (the people-shaped among the wild's)
    humanAttack: { group: "Voices", label: "A man attacking", about: "A man's effort grunt.", plays: "A bandit or a cultist (a man: a woman's voice isn't recorded yet) striking, loudest as its blow lands: now and then." },
    humanHurt: { group: "Voices", label: "A man hurt", about: "A man's pain grunt.", plays: "A bandit or a cultist (a man: a woman's voice isn't recorded yet) struck, no oftener than every 0.7 seconds." },
    humanDeath: { group: "Voices", label: "A man dying", about: "A man's dying groan.", plays: "A bandit or a cultist (a man: a woman's voice isn't recorded yet) dying." },
    humanRoughAttack: { group: "Voices", label: "A rough man attacking", about: "A deeper, rougher man's fight grunt.", plays: "The bandit chief (a man) striking, loudest as its blow lands: now and then." },
    humanRoughHurt: { group: "Voices", label: "A rough man hurt", about: "A rough man's pain grunt.", plays: "The bandit chief (a man) struck, no oftener than every 0.7 seconds." },
    humanRoughDeath: { group: "Voices", label: "A rough man dying", about: "A rough man's growl and agony.", plays: "The bandit chief (a man) dying." },

    // Folk at work (game.js ACTS: the folk's acts in the tavern, the smithy, the guild)
    clink: { group: "Folk at work", label: "Tankards", about: "Mugs knocked together, or one set down: sidequesting's ceramic mugs (one a double clink).", plays: "A patron's toast; a serving wench setting down a tankard." },
    pour: { group: "Folk at work", label: "Ale poured", about: "Beer poured into a glass, gurgling as it fills: from a tap (zembacraftworks's), and from a bottle (Kinoton's).", plays: "The barkeep pouring." },
    anvil: { group: "Folk at work", label: "Anvil", about: "A hammer on an anvil: a bright ring over the knock. The Versilian Community Sample Library's anvil, struck in the studio.", plays: "The smith forging, three blows at a time." },
    hiss: { group: "Folk at work", label: "Quenching", about: "Hot iron plunged in water, hissing as the steam dies away: rabban625's hot shovel quenched, and TRP's water on hot sauna stones.", plays: "The smith quenching the work." },
    bellows: { group: "Folk at work", label: "Bellows", about: "A great leather bellows' breath, its flaps fluttering: noisymichael's, in an old mill.", plays: "The smith's assistant pumping the bellows; the forge's fire stirred." },
    grind: { group: "Folk at work", label: "Grindstone", about: "A knife drawn over a turning grindstone, three or four strokes: florianreichelt's.", plays: "The smith's assistant cranking the grindstone." },
    rustle: { group: "Folk at work", label: "Papers", about: "A few dry crinkles of paper: keweldog's.", plays: "The guild's receptionist filing, and the folk reading." },
    distantHammer: { group: "Folk at work", label: "The smith at work, off", about: "A blacksmith hand-hammering at the smithy, recorded there by ldezem; heard from the street, through a low-pass filter.", plays: "By day, near a town's smithy: three or four blows every 5 to 12 seconds, from the smithy." },

    // The world (the environment's bus: ambience.js's beds, each looped round and round, and the
    // leaves; the made bird in place of a recorded one till it's in)
    bird: { group: "Birds", label: "A bird (made)", about: "A bird's chirp, made in code.", plays: "In the place of a recorded bird's song until it's downloaded." },
    leaves: { group: "The world", label: "Leaves", about: "A gust through a tree's leaves, swelling and dying away: bruno.auzet's.", plays: "From a tree within 22 metres, now and then (every 2.5 to 7 seconds)." },
    crackle: { group: "The world", label: "Hearth", about: "A few pops of a quiet fire: SKrafft's night campfire.", plays: "From the tavern's hearth, every 0.2 to 0.9 seconds." },
    windOpen: { group: "The world", label: "Wind over open land", about: "Dry grass rustling in the wind on an open plain: felix.blume's, in the Chilean desert. A 29-second loop.", plays: "Out on open land (meadow, farmland, heath, savannah, the badlands, the marsh, by the sea), always, under everything; half as loud in a town." },
    windForest: { group: "The world", label: "Wind in the trees", about: "Gusts through the trees of a wood: Nox_Sound's. A 37-second loop.", plays: "In the woods, the dark wood, the elves' wood and the jungle." },
    windHigh: { group: "The world", label: "Wind up high", about: "Wind singing over a mountain, a faint cricket under it: felix.blume's. A 31-second loop.", plays: "Up the mountains, on the snow and the tundra, and anywhere above 175 m; in a ruined keep and a watchtower." },
    nightLoop: { group: "The world", label: "Crickets", about: "Crickets in the night, calm and regular: Nox_Sound's. A 23-second loop.", plays: "After dark, rising as the light goes, on any land but the snow, the mountains and the sea; quieter in a town." },
    frogsLoop: { group: "The world", label: "Frogs", about: "A chorus of boreal chorus frogs: the National Park Service's (Neal Herbert). A 31-second loop.", plays: "After dark, in the marsh and round a lake." },
    streamLoop: { group: "The world", label: "A stream", about: "A calm stream running over stones: Nox_Sound's. A 23-second loop.", plays: "Within 35 metres of a stream or a narrow river, louder nearer." },
    riverLoop: { group: "The world", label: "A river", about: "A large, fast mountain river: Auxide_Audio's. A 33-second loop.", plays: "Within 60 metres of a river, louder nearer." },
    waterfallLoop: { group: "The world", label: "A waterfall", about: "A waterfall's roar: Nox_Sound's. A 25-second loop.", plays: "Within 90 metres of a river falling over a lip." },
    surfLoop: { group: "The world", label: "The sea", about: "Waves breaking on a beach in Portugal, three to a loop: VMan533's. A 37-second loop.", plays: "Within 120 metres of the sea." },
    lakeLapping: { group: "The world", label: "A lake", about: "Gentle waves lapping at a lake's edge: TRP's. A 28-second loop.", plays: "Within 45 metres of a lake." },
    creakTree: { group: "The world", label: "A tree creaking", about: "A tree creaking deep in the wind: felix.blume's, in Patagonia.", plays: "In the woods, from a tree near, every 25 to 70 seconds." },
    campfireLoop: { group: "The world", label: "A camp fire", about: "A small camp fire crackling: kyles's. A 31-second loop.", plays: "Within 16 metres of a camp fire." },
    brazierLoop: { group: "The world", label: "A brazier", about: "A close fire's roar: Nox_Sound's camp fire. An 11-second loop.", plays: "Within 10 metres of a lit brazier (at a guard post, at night); in a smithy, its forge; in a castle's undercroft." },
    rainLoop: { group: "The world", label: "Rain", about: "Light rain in the country: jmbphilmes's. A 34-second loop.", plays: "Not yet: there's no weather. In the studio." },
    thunder: { group: "The world", label: "Thunder", about: "Distant thunder rolling: richwise's and Fission9's.", plays: "Not yet: there's no weather. In the studio." },

    // Birds (the environment's bus: ambience.js CALLS)
    birdDay: { group: "Birds", label: "Birdsong", about: "A blackbird, a robin, a firecrest, a blackcap and a chaffinch, each singing alone: richwise's blackbird and Sacha.Julien's birdsong study.", plays: "By day, every 4 to 14 seconds, somewhere round the player: more often in the woods, less in a town or on dry land, none up high or on the snow." },
    birdDawn: { group: "Birds", label: "The dawn chorus", about: "Birds at first light, many at once: the National Park Service's dawn chorus at Mammoth Hot Springs (Jennifer Jerrett).", plays: "From first light until five minutes after sunrise, every 2.5 to 7 seconds." },
    crow: { group: "Birds", label: "A crow", about: "A crow calling from a cherry tree: Setuniman's.", plays: "By day over open land (farmland, meadow, heath, savannah, the badlands), every 20 to 50 seconds; now and then up high." },
    gull: { group: "Birds", label: "A gull", about: "A herring gull calling from a rooftop: Canardo55's.", plays: "By day within 150 metres of the sea, every 8 to 22 seconds." },
    owl: { group: "Birds", label: "An owl", about: "An owl hooting: Gerent's.", plays: "At night in the woods, and on open land (less often), every 25 to 60 seconds." },

    // Town and farm (ambience.js)
    townLoop: { group: "Town and farm", label: "A town", about: "The bustle of a narrow town: voices, children, footsteps (bushtobazaar's, in Chefchaouen, where no car can go). A 33-second loop.", plays: "In a town or a settlement, as much of it as is round the player; quieter at night." },
    marketLoop: { group: "Town and farm", label: "A market", about: "Craftsmen and voices in a medina: scholzn's, in Tunis. A 29-second loop.", plays: "By day, within 45 metres of a market's middle." },
    dogBark: { group: "Town and farm", label: "A dog", about: "A big dog barking (ScouseMouseJB's malamute), heard from a way off.", plays: "In a town, every 18 to 55 seconds (less often at night)." },
    chickens: { group: "Town and farm", label: "Hens", about: "Hens clucking: evsecrets's.", plays: "By day in a town, every 25 to 70 seconds." },
    rooster: { group: "Town and farm", label: "A cock crowing", about: "A cock crowing: lonemonk's.", plays: "At dawn, in a town or on farmland, every 12 to 35 seconds." },
    horseWhinny: { group: "Town and farm", label: "A horse", about: "A horse whinnying: 3bagbrew's and dontwanttobehere's.", plays: "By day in a town, every 45 to 120 seconds." },
    cowMoo: { group: "Town and farm", label: "Cattle", about: "A cow mooing: felix.blume's in the Limousin, and Mystikuum's.", plays: "By day on farmland and meadow, every 25 to 70 seconds, from far off; seldom in a town." },
    sheepBleat: { group: "Town and farm", label: "Sheep", about: "A sheep bleating out of doors: Yuval's.", plays: "By day on farmland and meadow, every 20 to 60 seconds; seldom in a town." },
    churchBell: { group: "Town and farm", label: "A church bell", about: "A church bell struck, ringing on: Nox_Sound's.", plays: "In a town at the hours of prayer (6, 9, 12, 15 and 18 o'clock), three strokes, from the church somewhere off." },

    // Indoors (ambience.js INDOORS)
    tavernLoop: { group: "Indoors", label: "A tavern", about: "A lively pub's crowd: ondondvo's, in Czechia. A 29-second loop.", plays: "In a tavern's taproom; quieter upstairs and in an adventurers' guild." },
    hearthLoop: { group: "Indoors", label: "A hearth", about: "A fire crackling gently: florianreichelt's. A 26-second loop.", plays: "In a tavern's taproom, louder nearer the hearth." },
    templeLoop: { group: "Indoors", label: "A temple", about: "The hush of an old church: its air and a low rumble (composingatnight's). A 21.5-second loop.", plays: "In a temple or an abbey; quieter in a town hall." },
    cryptLoop: { group: "Indoors", label: "A crypt", about: "A cellar's still air: kyles's. A 27-second loop.", plays: "In a crypt and a castle's undercroft; quieter in a keep." },
    caveDrips: { group: "Indoors", label: "Drips in a cave", about: "Water dripping in a small cave: Selector's. A 32-second loop.", plays: "In a cave; quieter in a crypt and a ruined keep." },
    lairLoop: { group: "Indoors", label: "The dragon's lair", about: "Steam belching and water sloshing deep in a spring: the National Park Service's Dragon's Mouth, in Yellowstone (David Restivo). A 31-second loop.", plays: "In the dragon's lair." },

    // Coins and trade (scripts/sounds/items.js)
    coins: { group: "Coins and trade", label: "A purse of coins", about: "A handful of coins shaken in a closed hand, a warm jingle: SpaceJoe's.", plays: "Gold off a felled foe; a share of a convoy's goods fallen on, in gold; buying or selling at a shop; paying for ale, a meal, a room or a blessing; hiring a follower." },
    coinPickup: { group: "Coins and trade", label: "Coins picked up", about: "A few coins chinking together as they're scooped up: SpaceJoe's.", plays: "Taking a sack or a chest's share with gold in it; putting on a ring or an amulet." },
    tradeDone: { group: "Coins and trade", label: "A trade done", about: "A coin shake, and a hand chime ringing over it (A or D, in the music's key).", plays: "A face-to-face trade with another player agreed and done." },
    buyDenied: { group: "Coins and trade", label: "Too dear", about: "A coin pouch dropped on a table: a soft, dull thud (Canakinsound's).", plays: "Anything refused for want of gold: a shop's wares, a trade, a room, a hire or a step through a guild's portal." },

    // In hand (scripts/sounds/items.js; audio/handling.js says which)
    pickup: { group: "In hand", label: "Picked up", about: "A leather quiver squeezed: a short creak of leather (Jan Schupke's).", plays: "Something picked up off the ground, found on a foe or taken back after it's thrown away; a weapon taken in hand from the pack." },
    drop: { group: "In hand", label: "Dropped", about: "A leather bag dropped on the floor: a dull thud (vintage2005's).", plays: "Something dropped on the ground; a creature's spoils left in a sack, or a reward left at the player's feet." },
    discard: { group: "In hand", label: "Thrown away", about: "A knife dropped on a carpet: a dull thud with a small bounce (Vrymaa's).", plays: "Something thrown away from the pack." },
    equipCloth: { group: "In hand", label: "Cloth put on", about: "Cloth rustling as it's pulled on (Kenney's).", plays: "A gambeson, trousers, a cloak or a wizard's hat put on or taken off; a bandage wound on." },
    equipLeather: { group: "In hand", label: "Leather put on", about: "A heavy leather jacket's creak and rustle (Vrymaa's).", plays: "A cap, a jerkin, bracers, gloves, a belt, breeches, boots or a quiver put on or taken off." },
    equipMail: { group: "In hand", label: "Mail put on", about: "Mail's rings rattling as it's shrugged on (artisticdude's).", plays: "A mail shirt or a hauberk put on or taken off (an elf's or a human's: an orc's is plate, a lizard's cloth)." },
    equipPlate: { group: "In hand", label: "Plate put on", about: "A steel pot set down on wood: a damped, hollow clank, as a helm or a breastplate is (Vrymaa's: no CC0 recording of real plate armour being handled was found).", plays: "A breastplate, a helm, plated gloves, gauntlets, vambraces, greaves or sabatons put on or taken off." },
    potionCork: { group: "In hand", label: "A pot uncorked", about: "A small glass vial uncorked: a little pop (Jan Schupke's).", plays: "A burn salve's pot opened." },
    potionDrink: { group: "In hand", label: "A draught drunk", about: "A vial uncorked, then two gulps (Jan Schupke's pop, Vrymaa's drink).", plays: "Any draught, potion or tankard drunk: healing, stamina, a cure, troll's blood." },
    eat: { group: "In hand", label: "Eating", about: "Bites of an apple, close (Vrymaa's).", plays: "A hot meal, boar or bear meat or frog's legs eaten." },
    scroll: { group: "In hand", label: "A scroll unrolled", about: "A scroll unrolling: a long paper crackle (spookymodem's).", plays: "A Scroll of Safety read." },
    bookOpen: { group: "In hand", label: "A book opened", about: "A heavy old book opened, its cover and pages (j1987's bible).", plays: "The spellbook or the journal opened; a tome read." },
    pageTurn: { group: "In hand", label: "A page turned", about: "A page riffled over (rubberduck's).", plays: "The pack's pages turned, and its tabs (Gear and Skills, Buy and Sell) changed." },
    mapUnfold: { group: "In hand", label: "A map unfolded", about: "A map unfolded, and stiff parchment unrolled (Breviceps's and Vrymaa's).", plays: "The world map opened." },
    packOpen: { group: "In hand", label: "The pack opened", about: "A strap's buckle undone and the leather creaking (Jan Schupke's sword sheath, standing in for a satchel's).", plays: "The pack opened." },
    packClose: { group: "In hand", label: "The pack closed", about: "The strap buckled again.", plays: "The pack closed." },
    chestOpen: { group: "In hand", label: "A chest opened", about: "A wooden chest's lid lifted: its latch, then its creak (The_Frisbee_of_Peace's chest and Vrymaa's cupboard).", plays: "A place's chest opening once it's cleared, the player's share in it." },
    chestClose: { group: "In hand", label: "A chest shut", about: "The lid shut: a thump.", plays: "The last of a chest's share taken." },
    lockpick: { group: "In hand", label: "A lock turned", about: "A key turned in a lockbox, its bolt drawn (Jan Schupke's).", plays: "A place's chest unlocked as it's cleared, before its lid's lifted." },
    quill: { group: "In hand", label: "A quill", about: "A sharp point scratching over stiff parchment (Vrymaa's: the CC0 recordings of real quills were too noisy).", plays: "A request taken, written in the journal; signing up at an adventurers' guild." },

    // The interface (scripts/sounds/items.js)
    wheel: { group: "The interface", label: "Action wheel", about: "A soft wooden tok: a woodblock (the Versilian Community Sample Library's), near F above the treble.", plays: "The action wheel opening, and turned to its other side." },
    wheelSelect: { group: "The interface", label: "Chosen on the wheel", about: "A fuller wooden tick, small things in a wooden box (Vrymaa's).", plays: "An action chosen on the wheel." },
    quickAction: { group: "The interface", label: "Quick action", about: "An arrow grabbed from a leather quiver: a quick rattle (Jan Schupke's).", plays: "A quick action used (its button, or keys 1 to 4)." },
    tap: { group: "The interface", label: "Tap", about: "A small single wooden tick, the softest of them all (Vrymaa's box).", plays: "A reply chosen in a talk; the world map's pin taken away." },
    talk: { group: "The interface", label: "Talk", about: "A card slid over felt: a soft, papery swish (Kenney's).", plays: "A talk begun." },
    denied: { group: "The interface", label: "Refused", about: "Two dull wooden knocks, the second softer: \"tok-tok, no\" (Kenney's).", plays: "A slice of the wheel that can't be used; anything refused but for gold (too far, on cooldown, no room); a request failed." },
    lock: { group: "The interface", label: "Target", about: "A key turning in a lock: one soft metallic click (Jan Schupke's).", plays: "An enemy chosen to fight." },

    // Cues (scripts/sounds/items.js: the Versilian Community Sample Library's, in the music's D Dorian)
    slain: { group: "Cues", label: "Slain", about: "Two hand chimes struck together, low on D.", plays: "A foe the player or a follower felled, or one the player fought in the last 30 seconds, hitting the ground." },
    fallen: { group: "Cues", label: "Fallen", about: "Three hand chimes falling to D, sombre.", plays: "The player falling, or a follower." },
    wake: { group: "Cues", label: "Waking", about: "Two hand chimes rising a fifth.", plays: "Waking again after falling; a spell learnt from a tome; a place cleared; a barracks put down, its town taken or not; asked to trade, or summoned, by another player." },
    levelUp: { group: "Cues", label: "Rising a rank", about: "A quick run up the folk harp, a hand chime on its top note.", plays: "A new rank in a skill, among the player's people or in the guilds; a school of magic come to its next tier; a spell grown stronger." },
    questDone: { group: "Cues", label: "A quest done", about: "A folk harp's run from D, then two hand chimes ringing.", plays: "A request handed in and done." },
    newsHeard: { group: "Cues", label: "News", about: "A small Nepalese hand bell.", plays: "News of the war where the player is: a fortification razed or fallen, an envoy arrived or struck down, a convoy fallen on; and, from a Knight up, their people's army's supplies not getting through." },
    pinSet: { group: "Cues", label: "A pin set", about: "One soft glockenspiel note.", plays: "A pin put on the world map." },
    breath: { group: "Cues", label: "Out of breath", about: "Someone panting after running hard.", plays: "The player running out of stamina." },
});

/** What else the studio can play, not one of SOUNDS: the wind, and the music in each place. */
export const LOOPS = Object.freeze({
    wind: { group: "The world", label: "The wind (made)", about: "A quiet wind made in code, a ten-second loop without a seam.", plays: "Out in the world, until a recorded wind is downloaded and blowing." },
});

/** The music, by where it's heard (each of sound.js's PLACES). */
export const MUSIC = Object.freeze({
    town: { label: "The town's score", about: "A Bard's Tale-style score in D Dorian, on recordings of real old instruments (recorder, ocarina, folk harp, strumstick, harpsichord, organ, chimes, frame drum).", plays: "Out in the world and the towns." },
    taproom: { label: "The tavern's jig", about: "A lively jig led by a lute (a classical guitar's nylon strings), with recorder and drum.", plays: "In a tavern's taproom." },
    upstairs: { label: "Upstairs in the tavern", about: "The tavern's jig, quieter and muffled, heard through the floor.", plays: "Upstairs in a tavern." },
    smithy: { label: "In a smithy", about: "The town's music as if through the smithy's walls, under the forge's roar.", plays: "In a smithy." },
    temple: { label: "In a temple", about: "The town's music hushed, far off through thick walls.", plays: "In a temple." },
    guild: { label: "In an adventurers' guild", about: "The tavern's jig, a little quieter: the guild's as lively.", plays: "In an adventurers' guild." },
    hall: { label: "In a town hall", about: "The town's music through the hall's windows.", plays: "In a town hall." },
    keep: { label: "In a keep", about: "The town's music far off through stone.", plays: "In a keep, a castle's or a citadel's." },
    undercroft: { label: "In an undercroft", about: "The town's music further off yet, under the keep's great hall.", plays: "In a castle keep's undercroft, with its smith, quartermaster and arcanist." },
    cave: { label: "In a cave", about: "The world outside barely heard.", plays: "In a cave." },
    lair: { label: "In the dragon's lair", about: "The world outside barely heard, deeper in.", plays: "In the dragon's lair." },
    crypt: { label: "In a crypt", about: "The world above barely heard through the floor.", plays: "In a crypt under a hall." },
    ruin: { label: "In a ruined keep", about: "The world outside through broken walls, open to the sky.", plays: "In a ruined keep." },
    tower: { label: "In a watchtower", about: "The world outside through the tower's stones.", plays: "In a broken watchtower." },
});
